name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare .env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "GIGACHAT_TOKEN=${{ secrets.GIGACHAT_TOKEN }}" >> .env
          echo "GOOGLE_SHEETS_CREDS=google_creds.json" >> .env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env

      - name: Prepare service account file
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          echo "$GOOGLE_CREDS_JSON" > google_creds.json

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY2 }}
          source: "."
          target: "/root/sociomind_bot"

      - name: Restart sociomind_bot service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY2 }}
          script: |
            cd /root/sociomind_bot
            pip install -r requirements.txt
            sudo systemctl restart sociomind_bot.service
